name: Node.js CI, Build and Test

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: move to server
        run: cd server
        
      - name: Use Node.js 18.16.1
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.1
          cache: "npm"
      - name: Install dependencies
        run: |
          cd ./server
          npm i
          
      - name: Running tests
        working-directory: ./server
        run: |
          cd ./server
          npm i
        